### ISSUE TITLE
Ti sta piacendo github?

### ISSUE THREAD

**Issue by Gabri432** [AnastasiaPonti/Ana#1]
Bazinga.

**Comment by AnastasiaPonti** [comment]
Ma ciaooo

**Comment by AnastasiaPonti** [comment]
> Bazinga.

Aspeee ma tu ti sei infiltrato nella mia repositoryyy OHHH esci fuori

**Comment by Gabri432** [comment]
> 

## Risposta
maiiiii

**Comment by AnastasiaPonti** [comment]
AIUTOOO no va viaaa gattinooo

**Comment by Gabri432** [comment]
> AIUTOOO no va viaaa gattinooo

# MUAHAHAHAHAH

#### Malvagità a portata di baffetti! :cat:

**Comment by AnastasiaPonti** [comment]
> > AIUTOOO no va viaaa gattinooo
> 
> # MUAHAHAHAHAH
> #### Malvagità a portata di baffetti! 🐱

😭😭😭

**Comment by Gabri432** [comment]
:pineapple: : "Come si chiama il profilo del dragan??"
:cat: : "Non lo saprai mai...MUAHAHAHAH!!"

**Comment by Gabri432** [comment]
> > > AIUTOOO no va viaaa gattinooo
> > 
> > 
> > # MUAHAHAHAHAH
> > #### Malvagità a portata di baffetti! 🐱
> 
> 😭😭😭

:pineapple: : "Come si chiama il profilo del dragan??"
:cat: : "Non lo saprai mai...MUAHAHAHAH!!"

**Comment by AnastasiaPonti** [comment]
> > > > AIUTOOO no va viaaa gattinooo
> > > 
> > > 
> > > # MUAHAHAHAHAH
> > > #### Malvagità a portata di baffetti! 🐱
> > 
> > 
> > 😭😭😭
> 
> 🍍 : "Come si chiama il profilo del dragan??" 🐱 : "Non lo saprai mai...MUAHAHAHAH!!"

Mai? Lo so da almeno 1 settimana, così come quello del Santini e di tanti altriiii... 😇 Ci manca solo la Cavaterra che tu già segui su instagram e siamo apposto!

**Comment by AnastasiaPonti** [comment]
Not an Issue
